### ISSUE TITLE
Error in IntelliJ IDEA 2016.1

### ISSUE THREAD

**Issue by jwjames83** [asebak/raspberrypi-intellij#58]
I'm trying to create a Raspberry Pi project and receive this error:

```
freemarker/template/Configuration
java.lang.NoClassDefFoundError: freemarker/template/Configuration
    at com.atsebak.embeddedlinuxjvm.utils.Template.toFile(Template.java:22)
    at com.atsebak.embeddedlinuxjvm.project.RPiJavaModuleBuilder$1.run(RPiJavaModuleBuilder.java:101)
    at com.intellij.util.DisposeAwareRunnable.run(DisposeAwareRunnable.java:82)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:344)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:336)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:184)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$5$2.run(ProjectManagerImpl.java:393)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:345)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: freemarker.template.Configuration PluginClassLoader[com.atsebak.raspberrypi, 1.11]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 26 more

```

**Comment by asebak** [comment]
fixed it and released plugin
