### ISSUE TITLE
Dependencies of SBT are copied to Raspberry, causing conflicts

### ISSUE THREAD

**Issue by seitfa** [asebak/raspberrypi-intellij#61]
I'm using this Plugin for Scala Development, wich worked fine for some time.

But starting with SBT 0.13, Scala itself gets resolved like a normal lib, see [http://stackoverflow.com/questions/22551430/in-sbt-0-13-does-scalaversion-still-control-the-version-of-scala-used-for-compi](http://stackoverflow.com/questions/22551430/in-sbt-0-13-does-scalaversion-still-control-the-version-of-scala-used-for-compi)

When using Scala with this plugin the depentendies of SBT (including conflicting Scala-Version), get copied to the Raspberry and get loaded during executin. SBT ist just the Build-Tool and is not needed an the Raspberry.

This causes errors like this:

`Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
    at akka.http.scaladsl.server.directives.LoggingMagnet$.forRequestResponseFromMarker(DebuggingDirectives.scala:69)
    at Service$class.$init$(AkkaHttpMicroservice.scala:81)
    at AkkaHttpMicroservice$.<init>(AkkaHttpMicroservice.scala:107)
    at AkkaHttpMicroservice$.<clinit>(AkkaHttpMicroservice.scala)
    at AkkaHttpMicroservice.main(AkkaHttpMicroservice.scala)
`

When executiong the same code localy, this problem does not exist

This problem could be reproduced with:
- Intellij 2016.1.3
- Scala-Plugin installed
- Version 1.20 of this plugin
- Activator-template "akka-http-microservice".

To work around this problem:
- Remove "SBT: sbt-and-plugin" from Dependencies under File > Project Structure > Modlues > *-build > Dependencies
- Delete Target-Folder on PI

**Comment by asebak** [comment]
how would you recommend i fix it programatically?

**Comment by seitfa** [comment]
My only idea is looking at the way it is done when the project get's executed locals => there has to be some difference in determining the Classpath and JARs getting loaded during execution.

**Comment by asebak** [comment]
Yeah that's done in this file: https://github.com/asebak/embeddedlinux-jvmdebugger-intellij/blob/master/src/com/atsebak/embeddedlinuxjvm/services/ClasspathService.java the method is invokeFindDeployedJars you can take a look at it and see if there's an issue with that code.
