### ISSUE TITLE
Classpath problem using multi-module configuration

### ISSUE THREAD

**Issue by vdegrandpre** [asebak/raspberrypi-intellij#62]
Hi @asebak ,

I am developing a multi-module project that was started as an Android one and now ported to pure Java. When sending to Raspberry Pi, the plugins compiles everything and the classpath conflicts between modules dependencies.

Can you add module's classpath support to your plugin ? That would make everything really helpful.

If not, can you point some path of resolution ?

Here is one error that I get :

Exception in thread "Thread-0" java.lang.VerifyError: Cannot inherit from final class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)

Best,
Vincent de Grandpré

**Comment by asebak** [comment]
It's tough for me at this time but if you want to create a pull request to support multiple modules than that would be great.

**Comment by asebak** [comment]
Should be fixed in next release
